version: '3'

networks:
  laravel_local:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    environment:
      production: 0
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel_local

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - laravel_local

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ../:/var/www/html
      # - /usr/local/etc/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - laravel_local

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel_local

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ../:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel_local

volumes:
  mysql:
    external: true
